# Run coverage report and upload it to CodeClimate
name: Coverage
on:
  push:
    branches: [master]
jobs:
  coverage:
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 10
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          extensions: mbstring
          coverage: pcov
      - name: Install composer dependencies
        uses: ramsey/composer-install@v3
        with:
          composer-options: "--prefer-dist --optimize-autoloader"
      - name: Build the code coverage report
        run: composer coverage:clover
      - name: Upload Scrutinizer coverage
        uses: sudo-bot/action-scrutinizer@latest
        with:
          cli-args: "--format=php-clover clover.xml"
